# Generated by Django 4.2.7 on 2023-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("motion_file", models.FileField(upload_to="motions/")),
            ],
        ),
    ]
