# Generated by Django 4.2.7 on 2023-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "process",
            "0003_achievement_matchrecord_userachievement_delete_video_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_token", models.CharField(max_length=50)),
                ("sex", models.CharField(db_comment="성별", max_length=1)),
                ("years_playing", models.IntegerField(db_comment="구력")),
                ("grade", models.CharField(db_comment="급수", max_length=10)),
                ("handedness", models.CharField(db_comment="주로 쓰는 손", max_length=5)),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="achievement",
            table="Achievement",
        ),
        migrations.AlterModelTable(
            name="matchrecord",
            table="Match_Record",
        ),
        migrations.AlterModelTable(
            name="motion",
            table="Motion",
        ),
        migrations.AlterModelTable(
            name="userachievement",
            table="User_Achievement",
        ),
    ]
