# Generated by Django 4.2.7 on 2023-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "process",
            "0004_user_alter_achievement_table_alter_matchrecord_table_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_token", models.CharField(max_length=50)),
                ("sex", models.CharField(db_comment="성별", max_length=1)),
                ("years_playing", models.IntegerField(db_comment="구력")),
                ("grade", models.CharField(db_comment="급수", max_length=10)),
                ("handedness", models.CharField(db_comment="주로 쓰는 손", max_length=5)),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Player",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                (
                    "relation_id",
                    models.AutoField(
                        db_comment="관계 아이디", primary_key=True, serialize=False
                    ),
                ),
                ("player_token", models.CharField(max_length=50)),
                ("achieve", models.IntegerField(db_comment="업적 아이디")),
                (
                    "cumulative_val",
                    models.IntegerField(blank=True, db_comment="누적치", null=True),
                ),
                (
                    "achieve_year_month",
                    models.DateField(blank=True, db_comment="업적년월", null=True),
                ),
                (
                    "d_achieve_date",
                    models.DateField(blank=True, db_comment="D등급 달성일자", null=True),
                ),
                (
                    "c_achieve_date",
                    models.DateField(blank=True, db_comment="C등급 달성일자", null=True),
                ),
                (
                    "b_achieve_date",
                    models.DateField(blank=True, db_comment="B등급 달성일자", null=True),
                ),
                (
                    "a_achieve_date",
                    models.DateField(blank=True, db_comment="A등급 달성일자", null=True),
                ),
                (
                    "s_achieve_date",
                    models.DateField(blank=True, db_comment="S등급 달성일자", null=True),
                ),
                (
                    "last_achieve_date",
                    models.DateField(blank=True, db_comment="최근 달성일자", null=True),
                ),
            ],
            options={
                "db_table": "Player_Achievement",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
    ]
