# Generated by Django 4.2.7 on 2023-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0006_delete_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwingScore",
            fields=[
                (
                    "swing_score_id",
                    models.AutoField(
                        db_comment="스윙스코어 아이디", primary_key=True, serialize=False
                    ),
                ),
                ("swing_id", models.IntegerField(db_comment="스윙 아이디")),
                ("score", models.IntegerField(db_comment="스윙 점수")),
                ("swing_type", models.CharField(max_length=2)),
                ("match_id", models.IntegerField(db_comment="경기 아이디")),
            ],
            options={
                "db_table": "Swing_Score",
                "managed": False,
            },
        ),
    ]
