# Generated by Django 4.2.7 on 2023-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "player_token",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("sex", models.CharField(db_comment="성별", max_length=1)),
                ("years_playing", models.IntegerField(db_comment="구력")),
                ("grade", models.CharField(db_comment="급수", max_length=10)),
                ("handedness", models.CharField(db_comment="주로 쓰는 손", max_length=5)),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Player",
                "managed": False,
            },
        ),
    ]
